import { ImageResponse } from "@vercel/og";

export const config = { runtime: "edge" };

export default async function handler(req) {
  const { address, total = "$0", tokens = "N/A", change = "0%" } = Object.fromEntries(
    new URL(req.url).searchParams
  );

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          background: "linear-gradient(145deg, #0B0C10, #1F2833)",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          color: "#C5C6C7",
          fontFamily: "monospace",
        }}
      >
        <div style={{ fontSize: 64, color: "#66FCF1", marginBottom: 20 }}>
          Wallet Analyzer
        </div>
        <div style={{ fontSize: 32 }}>Address: {address.slice(0, 6)}...{address.slice(-4)}</div>
        <div style={{ fontSize: 28, color: "#45A29E", marginTop: 10 }}>
          Total Value: {total}
        </div>
        <div style={{ fontSize: 24, marginTop: 8 }}>Top Tokens: {tokens}</div>
        <div
          style={{
            fontSize: 24,
            marginTop: 8,
            color: change.startsWith("-") ? "#FF6B6B" : "#66FCF1",
          }}
        >
          7D Change: {change}
        </div>
        <div style={{ fontSize: 20, color: "#999", marginTop: 50 }}>
          Generated by Farcaster Analyzer
        </div>
      </div>
    ),
    { width: 1000, height: 1000 }
  );
}
